// Existing action types
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

// New action types for finding product by ID
export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST';
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS';
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE';

// New action types for finding products by category
export const FIND_PRODUCT_BY_CATEGORY_REQUEST = 'FIND_PRODUCT_BY_CATEGORY_REQUEST';
export const FIND_PRODUCT_BY_CATEGORY_SUCCESS = 'FIND_PRODUCT_BY_CATEGORY_SUCCESS';
export const FIND_PRODUCT_BY_CATEGORY_FAILURE = 'FIND_PRODUCT_BY_CATEGORY_FAILURE';